{"name": "Тест раздела \"В работе\"", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame\n  (Session info: chrome=124.0.6367.202); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception\nStacktrace:\n\tGetHandleVerifier [0x00007FF6824E1562+60802]\n\t(No symbol) [0x00007FF68245AC62]\n\t(No symbol) [0x00007FF682317CE4]\n\t(No symbol) [0x00007FF68231DE26]\n\t(No symbol) [0x00007FF6823201DB]\n\t(No symbol) [0x00007FF682320280]\n\t(No symbol) [0x00007FF682360E0B]\n\t(No symbol) [0x00007FF68238AB7A]\n\t(No symbol) [0x00007FF68235A7C6]\n\t(No symbol) [0x00007FF68238AD90]\n\t(No symbol) [0x00007FF6823AA224]\n\t(No symbol) [0x00007FF68238A923]\n\t(No symbol) [0x00007FF682358FEC]\n\t(No symbol) [0x00007FF682359C21]\n\tGetHandleVerifier [0x00007FF6827E41FD+3217949]\n\tGetHandleVerifier [0x00007FF682826197+3488183]\n\tGetHandleVerifier [0x00007FF68281F11F+3459391]\n\tGetHandleVerifier [0x00007FF68259B926+823622]\n\t(No symbol) [0x00007FF682465FFF]\n\t(No symbol) [0x00007FF682460F24]\n\t(No symbol) [0x00007FF6824610B2]\n\t(No symbol) [0x00007FF682451904]\n\tBaseThreadInitThunk [0x00007FFEA6447344+20]\n\tRtlUserThreadStart [0x00007FFEA6F626B1+33]", "trace": "self = <tests.test_order_list.TestOrderList object at 0x0000023AD8E41730>\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"be50cc52cfc1b4086c5dac4ea3e882ce\")>\nuser = {'email': 'gtekwojinl@gmail.com', 'json': {'accessToken': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NDE... 'user': {'email': 'gtekwojinl@gmail.com', 'name': 'fbjrbjdfix'}}, 'name': 'fbjrbjdfix', 'password': 'tszfyxkfme', ...}\n\n    @allure.title('Тест раздела \"В работе\"')\n    def test_in_work_list(self, driver, user):\n        page = OrderList(driver)\n        page.open(Url.ORDER_LIST_PAGE)\n        response = helpers.create_order(user)\n        order_number = response.json()['order']['number']\n>       assert str(order_number) >= page.get_in_work_order_number()\n\ntests\\test_order_list.py:62: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\order_list_page.py:33: in get_in_work_order_number\n    return self.get_text(OrderListLocators.ORDERS_IN_WORK)\npages\\base_page.py:38: in get_text\n    return WebDriverWait(self.driver, time).until(ec.presence_of_element_located(locator)).text\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py:90: in text\n    return self._execute(Command.GET_ELEMENT_TEXT)[\"value\"]\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py:395: in _execute\n    return self._parent.execute(command, params)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:347: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x0000023AD8FD7260>\nresponse = {'status': 404, 'value': '{\"value\":{\"error\":\"stale element reference\",\"message\":\"stale element reference: stale elemen...07FF682451904]\\\\n\\\\tBaseThreadInitThunk [0x00007FFEA6447344+20]\\\\n\\\\tRtlUserThreadStart [0x00007FFEA6F626B1+33]\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame\nE         (Session info: chrome=124.0.6367.202); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception\nE       Stacktrace:\nE       \tGetHandleVerifier [0x00007FF6824E1562+60802]\nE       \t(No symbol) [0x00007FF68245AC62]\nE       \t(No symbol) [0x00007FF682317CE4]\nE       \t(No symbol) [0x00007FF68231DE26]\nE       \t(No symbol) [0x00007FF6823201DB]\nE       \t(No symbol) [0x00007FF682320280]\nE       \t(No symbol) [0x00007FF682360E0B]\nE       \t(No symbol) [0x00007FF68238AB7A]\nE       \t(No symbol) [0x00007FF68235A7C6]\nE       \t(No symbol) [0x00007FF68238AD90]\nE       \t(No symbol) [0x00007FF6823AA224]\nE       \t(No symbol) [0x00007FF68238A923]\nE       \t(No symbol) [0x00007FF682358FEC]\nE       \t(No symbol) [0x00007FF682359C21]\nE       \tGetHandleVerifier [0x00007FF6827E41FD+3217949]\nE       \tGetHandleVerifier [0x00007FF682826197+3488183]\nE       \tGetHandleVerifier [0x00007FF68281F11F+3459391]\nE       \tGetHandleVerifier [0x00007FF68259B926+823622]\nE       \t(No symbol) [0x00007FF682465FFF]\nE       \t(No symbol) [0x00007FF682460F24]\nE       \t(No symbol) [0x00007FF6824610B2]\nE       \t(No symbol) [0x00007FF682451904]\nE       \tBaseThreadInitThunk [0x00007FFEA6447344+20]\nE       \tRtlUserThreadStart [0x00007FFEA6F626B1+33]\n\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py:229: StaleElementReferenceException"}, "steps": [{"name": "Открываем браузер по ссылке", "status": "passed", "parameters": [{"name": "url", "value": "'https://stellarburgers.nomoreparties.site/feed'"}], "start": 1715538122025, "stop": 1715538124481}, {"name": "Создаем заказ", "status": "passed", "parameters": [{"name": "user", "value": "{'email': 'gtekwojinl@gmail.com', 'password': 'tszfyxkfme', 'name': 'fbjrbjdfix', 'status_code': 200, 'json': {'success': True, 'user': {'email': 'gtekwojinl@gmail.com', 'name': 'fbjrbjdfix'}, 'accessToken': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NDEwNmRiOWVkMjgwMDAxYjQwZGNmYyIsImlhdCI6MTcxNTUzNzYyNywiZXhwIjoxNzE1NTM4ODI3fQ.WEVZ9cReFYo-aPdYFlj-HsiyRZvfv16tIBQpO3CVMrs', 'refreshToken': 'baafa308c6340ea90707fed5824b59133336e150cc9a900fc82107368bf27f4a4db067ba2934bbf4'}}"}], "start": 1715538124481, "stop": 1715538126718}, {"name": "Собираем номер заказа в работе", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame\n  (Session info: chrome=124.0.6367.202); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception\nStacktrace:\n\tGetHandleVerifier [0x00007FF6824E1562+60802]\n\t(No symbol) [0x00007FF68245AC62]\n\t(No symbol) [0x00007FF682317CE4]\n\t(No symbol) [0x00007FF68231DE26]\n\t(No symbol) [0x00007FF6823201DB]\n\t(No symbol) [0x00007FF682320280]\n\t(No symbol) [0x00007FF682360E0B]\n\t(No symbol) [0x00007FF68238AB7A]\n\t(No symbol) [0x00007FF68235A7C6]\n\t(No symbol) [0x00007FF68238AD90]\n\t(No symbol) [0x00007FF6823AA224]\n\t(No symbol) [0x00007FF68238A923]\n\t(No symbol) [0x00007FF682358FEC]\n\t(No symbol) [0x00007FF682359C21]\n\tGetHandleVerifier [0x00007FF6827E41FD+3217949]\n\tGetHandleVerifier [0x00007FF682826197+3488183]\n\tGetHandleVerifier [0x00007FF68281F11F+3459391]\n\tGetHandleVerifier [0x00007FF68259B926+823622]\n\t(No symbol) [0x00007FF682465FFF]\n\t(No symbol) [0x00007FF682460F24]\n\t(No symbol) [0x00007FF6824610B2]\n\t(No symbol) [0x00007FF682451904]\n\tBaseThreadInitThunk [0x00007FFEA6447344+20]\n\tRtlUserThreadStart [0x00007FFEA6F626B1+33]\n\n", "trace": "  File \"C:\\Users\\Пользователь\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Пользователь\\PycharmProjects\\Diplom\\Diplom_3\\pages\\order_list_page.py\", line 33, in get_in_work_order_number\n    return self.get_text(OrderListLocators.ORDERS_IN_WORK)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Пользователь\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Пользователь\\PycharmProjects\\Diplom\\Diplom_3\\pages\\base_page.py\", line 38, in get_text\n    return WebDriverWait(self.driver, time).until(ec.presence_of_element_located(locator)).text\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Пользователь\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 90, in text\n    return self._execute(Command.GET_ELEMENT_TEXT)[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Пользователь\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 395, in _execute\n    return self._parent.execute(command, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Пользователь\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Пользователь\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Собираем текст с элемента", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame\n  (Session info: chrome=124.0.6367.202); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception\nStacktrace:\n\tGetHandleVerifier [0x00007FF6824E1562+60802]\n\t(No symbol) [0x00007FF68245AC62]\n\t(No symbol) [0x00007FF682317CE4]\n\t(No symbol) [0x00007FF68231DE26]\n\t(No symbol) [0x00007FF6823201DB]\n\t(No symbol) [0x00007FF682320280]\n\t(No symbol) [0x00007FF682360E0B]\n\t(No symbol) [0x00007FF68238AB7A]\n\t(No symbol) [0x00007FF68235A7C6]\n\t(No symbol) [0x00007FF68238AD90]\n\t(No symbol) [0x00007FF6823AA224]\n\t(No symbol) [0x00007FF68238A923]\n\t(No symbol) [0x00007FF682358FEC]\n\t(No symbol) [0x00007FF682359C21]\n\tGetHandleVerifier [0x00007FF6827E41FD+3217949]\n\tGetHandleVerifier [0x00007FF682826197+3488183]\n\tGetHandleVerifier [0x00007FF68281F11F+3459391]\n\tGetHandleVerifier [0x00007FF68259B926+823622]\n\t(No symbol) [0x00007FF682465FFF]\n\t(No symbol) [0x00007FF682460F24]\n\t(No symbol) [0x00007FF6824610B2]\n\t(No symbol) [0x00007FF682451904]\n\tBaseThreadInitThunk [0x00007FFEA6447344+20]\n\tRtlUserThreadStart [0x00007FFEA6F626B1+33]\n\n", "trace": "  File \"C:\\Users\\Пользователь\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Пользователь\\PycharmProjects\\Diplom\\Diplom_3\\pages\\base_page.py\", line 38, in get_text\n    return WebDriverWait(self.driver, time).until(ec.presence_of_element_located(locator)).text\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Пользователь\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 90, in text\n    return self._execute(Command.GET_ELEMENT_TEXT)[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Пользователь\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 395, in _execute\n    return self._parent.execute(command, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Пользователь\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Пользователь\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "parameters": [{"name": "locator", "value": "('xpath', '//*[contains(@class, \"orderListReady\")]//li[contains(@class, \"digits-default\")]')"}, {"name": "time", "value": "15"}], "start": 1715538126719, "stop": 1715538126783}], "start": 1715538126719, "stop": 1715538126790}], "parameters": [{"name": "driver", "value": "'chrome'"}], "start": 1715538122025, "stop": 1715538126793, "uuid": "ac4e5982-17d1-4672-a6e7-e09653d0d584", "historyId": "27f8a51e391a0a6107e0376c714dc495", "testCaseId": "e78e473268d174465fe7846577e4b37f", "fullName": "tests.test_order_list.TestOrderList#test_in_work_list", "labels": [{"name": "story", "value": "Тесты ленты заказов"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_order_list"}, {"name": "subSuite", "value": "TestOrderList"}, {"name": "host", "value": "DESKTOP-9RKVCCS"}, {"name": "thread", "value": "8616-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order_list"}]}